<?php
namespace Database\Seeders;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user = [
            [
                'name' => "Student Raa",
                'headline' => "Web Developer",
                'email' => "student@gmail.com",
                'bio' => "I am a web developer",
                'image' => '/default-images/avatar/student_girl.png',
                'password' => bcrypt("12345678"),
                'role' => 'student',
                'approval_status' => 'pending',
                'account_status' => 'enabled',
                'facebook' => 'https://www.facebook.com/sethsopheara',
                'x' => 'https://www.facebook.com/sethsopheara',
                'linkedin' => 'https://www.facebook.com/sethsopheara',
                'website' => 'https://www.facebook.com/sethsopheara',
                'github' => 'https://www.facebook.com/sethsopheara',
            ],
            [
                'name' => "Teacher Raa",
                'headline' => "Web Developer",
                'email' => "teacher@gmail.com",
                'bio' => "I am a web developer",
                'image' => '/default-images/avatar/teacher.png',
                'password' => bcrypt("12345678"),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'account_status' => 'enabled',
                'facebook' => 'https://www.facebook.com/sethsopheara',
                'x' => 'https://www.facebook.com/sethsopheara',
                'linkedin' => 'https://www.facebook.com/sethsopheara',
                'website' => 'https://www.facebook.com/sethsopheara',
                'github' => 'https://www.facebook.com/sethsopheara',
            ],
            [
                'name' => 'Teacher John',
                'headline' => 'Full Stack Web Developer',
                'email' => 'teacher1@gmail.com',
                'bio' => 'Experienced Full Stack Developer.',
                'image' => '/default-images/avatar/teacher.png',
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'account_status' => 'enabled',
                'facebook' => 'https://facebook.com/john',
                'x' => 'https://x.com/john',
                'linkedin' => 'https://linkedin.com/in/john',
                'website' => 'https://john.dev',
                'github' => 'https://github.com/john',
            ],
            [
                'name' => 'Teacher Emma',
                'headline' => 'Laravel Developer',
                'email' => 'teacher2@gmail.com',
                'bio' => 'Laravel and PHP expert.',
                'image' => '/default-images/avatar/teacher.png',
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'account_status' => 'enabled',
                'facebook' => 'https://facebook.com/emma',
                'x' => 'https://x.com/emma',
                'linkedin' => 'https://linkedin.com/in/emma',
                'website' => 'https://emma.dev',
                'github' => 'https://github.com/emma',
            ],
            [
                'name' => 'Teacher David',
                'headline' => 'Frontend Developer',
                'email' => 'teacher3@gmail.com',
                'bio' => 'Vue.js and React developer.',
                'image' => '/default-images/avatar/teacher.png',
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'account_status' => 'enabled',
                'facebook' => 'https://facebook.com/david',
                'x' => 'https://x.com/david',
                'linkedin' => 'https://linkedin.com/in/david',
                'website' => 'https://david.dev',
                'github' => 'https://github.com/david',
            ],
            [
                'name' => 'Teacher Sophia',
                'headline' => 'Backend Developer',
                'email' => 'teacher4@gmail.com',
                'bio' => 'Node.js and Laravel specialist.',
                'image' => '/default-images/avatar/teacher.png',
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'account_status' => 'enabled',
                'facebook' => 'https://facebook.com/sophia',
                'x' => 'https://x.com/sophia',
                'linkedin' => 'https://linkedin.com/in/sophia',
                'website' => 'https://sophia.dev',
                'github' => 'https://github.com/sophia',
            ],
            [
                'name' => 'Teacher Michael',
                'headline' => 'Mobile App Developer',
                'email' => 'teacher5@gmail.com',
                'bio' => 'Flutter and Android developer.',
                'image' => '/default-images/avatar/teacher.png',
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'account_status' => 'enabled',
                'facebook' => 'https://facebook.com/michael',
                'x' => 'https://x.com/michael',
                'linkedin' => 'https://linkedin.com/in/michael',
                'website' => 'https://michael.dev',
                'github' => 'https://github.com/michael',
            ],
            [
                'name' => 'Teacher Olivia',
                'headline' => 'UI/UX Designer',
                'email' => 'teacher6@gmail.com',
                'bio' => 'Creative UI/UX designer.',
                'image' => '/default-images/avatar/teacher.png',
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'account_status' => 'enabled',
                'facebook' => 'https://facebook.com/olivia',
                'x' => 'https://x.com/olivia',
                'linkedin' => 'https://linkedin.com/in/olivia',
                'website' => 'https://olivia.dev',
                'github' => 'https://github.com/olivia',
            ],
            [
                'name' => 'Teacher Daniel',
                'headline' => 'DevOps Engineer',
                'email' => 'teacher7@gmail.com',
                'bio' => 'Docker and AWS enthusiast.',
                'image' => '/default-images/avatar/teacher.png',
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'account_status' => 'enabled',
                'facebook' => 'https://facebook.com/daniel',
                'x' => 'https://x.com/daniel',
                'linkedin' => 'https://linkedin.com/in/daniel',
                'website' => 'https://daniel.dev',
                'github' => 'https://github.com/daniel',
            ],
            [
                'name' => 'Teacher Isabella',
                'headline' => 'Data Scientist',
                'email' => 'teacher8@gmail.com',
                'bio' => 'Python and Machine Learning.',
                'image' => '/default-images/avatar/teacher.png',
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'account_status' => 'enabled',
                'facebook' => 'https://facebook.com/isabella',
                'x' => 'https://x.com/isabella',
                'linkedin' => 'https://linkedin.com/in/isabella',
                'website' => 'https://isabella.dev',
                'github' => 'https://github.com/isabella',
            ],
            [
                'name' => 'Teacher James',
                'headline' => 'Cyber Security Expert',
                'email' => 'teacher9@gmail.com',
                'bio' => 'Ethical hacker and security trainer.',
                'image' => '/default-images/avatar/teacher.png',
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'account_status' => 'enabled',
                'facebook' => 'https://facebook.com/james',
                'x' => 'https://x.com/james',
                'linkedin' => 'https://linkedin.com/in/james',
                'website' => 'https://james.dev',
                'github' => 'https://github.com/james',
            ],
            [
                'name' => 'Teacher Mia',
                'headline' => 'AI Engineer',
                'email' => 'teacher10@gmail.com',
                'bio' => 'Artificial Intelligence instructor.',
                'image' => '/default-images/avatar/teacher.png',
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'account_status' => 'enabled',
                'facebook' => 'https://facebook.com/mia',
                'x' => 'https://x.com/mia',
                'linkedin' => 'https://linkedin.com/in/mia',
                'website' => 'https://mia.dev',
                'github' => 'https://github.com/mia',
            ],
        ];
        User::insert($user);
    }
}
